### PR TITLE
[WIP] Particle Effects

### PR DESCRIPTION
**Pull request by ProgHaj**
## Description
GitHub issue: #20 
- [ ] Blood particles when units die
- [x] Level up
- [ ] Critical hit
- [x] Implosion ability effect

## How to test / set up
1. Enter Magnus.unity scene.
2. Play, use keyboard.

## Code hygiene
- [ ] The code handles errors gracefully
- [ ] The code doesn't contain unnecesary commented out code
- [ ] The code doesn't contain spamming/forgotten/unclear Debug.Log()s
- [ ] The code is properly formatted

### CODE REVIEW

**Comment by ProgHaj** [comment]
I added an initial level up and some sort of implosion for magicians spell, would be nice if I could get some feedback (too much? what's good/bad?). Is it over the top? Should I add more?

image

image

image

image

image

image

image

image

image


The left one being level up and the right one being the ability.

Test it out yourselves.

**Comment by ProgHaj** [comment]
I saw that @theyuppi had done a blood spawning effect, is that something we are going to use/is currently in development?

**Comment by maakep** [comment]
Holy fuck tbh.

The ability looks awesome! I was thinking, how does it work if you spawn it additively? Like adding one of those particles for each enemy hit, to even further emphasize getting more health the more enemies you hit? Really not needed, the particles in its self looks awesome.

Levelling up also looks great. 

What probably looks weird is our mixed perspectives: the environment is one angle, the characters another angle and particles / projectiles another. But lets ignore that for now, I think this looks great!

**Comment by maakep** [comment]
Regarding the existing Particle Systems I think they're placeholders; they're in the game, a quick flash of red  dots (called Blood) when you kill someone, a quick flash or yellow when you level up (called Hit).

Have you looked at the Particle System and how to incorporate new Particles in the ParticleSpawner (rename to ParticleManager or something standardized for such things? ParticleSpawner is pretty descreptive though, since that's its actual function, it's just confusing when we have AudioManager, ParticleSpawner, ConversationHandler, etc, which are pretty similar)

**Comment by ProgHaj** [comment]
Thanks for the feedback! :bowing_man: 
I could try adding it additively, I'm not quite sure how to do it as we speak but I will look into it.

Thanks for pointing me in the correct direction regarding ParticleSpawner, haven't checked it out yet.

We should probably standardize all the managers, and probably standardize how we use them (some of them are statics, some are singletons if I recall correctly.)

**Comment by maakep** [comment]
What I mean by additively (perhaps that's not the correct term) is just spamming the same animation at the same position. So instead of doign 1 particle spawn when ability is used, we spawn 1 particle system for every enemy hit, making it look more powerful/more healing per enemy. 

Or perhaps having 1 for damage 1 for heal, so we spawn 1 heal for every enemy but only 1 damage.

We don't need to do this though, I was just speculating. It looks great as it is.

**Comment by theyuppi** [comment]
You can scroll in the browser to get a preview of the effect... Neat!
When you do stuff like splatter keep in mind that it should work for several enemies at once, so don't overdo it unless you have to since if one kills 5 enemies at once the screen shouldn't be fully covered. 
Haven't seen how it looks ingame, but probably great!
You can play around with stuff like random rotation of the effect, have different subemitters that you randomly pick from or slightly different spreadsheets depending on how you made it. Why? Even a slight difference in the effects will make it feel more alive.

**Comment by maakep** [comment]
Ohhhh I thought the particle effect you showed was the SiphonBlood ability... The one where you damage an area and heal for every unit.

**Comment by maakep** [comment]
Had some issues:
Assertion failed: Removing Assets/Particles/LevelUp because the asset does not exist.

So the LevelUp.meta is removed when unity is building. And the particle effects are just pink arrows closing in on the player: 

image



and btw, you don't clone branches 😁 and checking out the branch as a part of testing the branch goes without saying!

**Comment by ProgHaj** [comment]
It is the SiphonBlood ability I was making it for, not the blood effect ;)

Thanks!

**Comment by ProgHaj** [comment]
Ops, forgot to include the files in the commit :1st_place_medal: 
They are pushed now!

**Review by ProgHaj — COMMENTED** [review]
forgot*

**Pull request merged**
